### PR TITLE
Add commonjs / npm support

### PR DESCRIPTION
**Pull request by mattlewis92**
Hi great module!

I'd like to consume it from npm via webpack so I've added support for that in this PR.

After merging + any time you release a new version you will just need to run `npm publish` to publish to npm.

Thanks!

### CODE REVIEW

**Comment by m43nu** [comment]
Thanks for that :+1:

**Comment by mattlewis92** [comment]
Great, thank you! Could you also publish it to npm (`npm publish`) from the root of the repo.

**Comment by m43nu** [comment]
Sure, it's done

**Comment by mattlewis92** [comment]
Great, thank you!

**Pull request merged**
